// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tsuKeysAPIProject.DBContext;

#nullable disable

namespace tsuKeysAPIProject.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240217060936_RequestKeyTableAdd")]
    partial class RequestKeyTableAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tsuKeysAPIProject.DBContext.Models.BlackToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Blacktoken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlackTokens");
                });

            modelBuilder.Entity("tsuKeysAPIProject.DBContext.Models.Key", b =>
                {
                    b.Property<string>("ClassroomNumber")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClassroomNumber");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("tsuKeysAPIProject.DBContext.Models.KeyRequest", b =>
                {
                    b.Property<string>("ClassroomNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndOfBooking")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyOwner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyRecipient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClassroomNumber");

                    b.ToTable("KeyRequest");
                });

            modelBuilder.Entity("tsuKeysAPIProject.DBContext.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
